name = "SuperLU"
uuid = "5e54adbb-e59a-4a64-a24f-c65aa99e667d"
version = "0.2.0"
authors = ["Li-Xun Cai, <cailixun23]@example.com>"]

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearSolve = "7ed4a6bd-45f5-4d41-b270-4a48e9bafcae"
OpenBLAS32_jll = "656ef2d0-ae68-5445-9ca0-591084a874a2"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SuperLU_MT_jll = "00982de7-9f76-5194-84e1-476c61fcc171"

[compat]
LinearSolve = "3"
OpenBLAS32_jll = "0.3.9 - 0.3.99"
SciMLBase = "2"
SuperLU_MT_jll = "3.1.0"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestItemRunner = "f8b46487-2199-4994-9208-9a1283c18c0a"

[targets]
test = ["Test", "TestItemRunner"]
