name = "SuperLU"
uuid = "5e54adbb-e59a-4a64-a24f-c65aa99e667d"
version = "0.1.0"
authors = ["Your Name <your.email@example.com>"]

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearSolve = "7ed4a6bd-45f5-4d41-b270-4a48e9bafcae"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SuperLU_jll = "f391fee2-5786-5cc9-9662-0e362ec949e2"

[weakdeps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"

[extensions]
CUDAExt = "CUDA"
LinearSolveExt = ["LinearSolve", "SciMLBase"]

[compat]
CUDA = "5"
LinearSolve = "3"
SciMLBase = "2"
SuperLU_jll = "5"
julia = "1.9"

[extras]
LinearSolve = "7ed4a6bd-45f5-4d41-b270-4a48e9bafcae"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestItemRunner = "f8b46487-2199-4994-9208-9a1283c18c0a"

[targets]
test = ["LinearSolve", "SciMLBase", "Test", "TestItemRunner"]
